# Site settings

title: Йов
email: boretskyi@yov.com.ua
description: Могилянська колективна платформа
keywords: yov, могилянка, наукма, кма, брюховецький, квіт, мелешевич, студенти, спудеї, йов, іов, борецький, naukma, kma, академія, могилянська, могилянський, вісник, бонет, плацераці
baseurl: ""
url: "http://yov.com.ua"
twitter_username: yovkma
facebook_username: yovkma

collections:
- events

# Navigation

navigation:
- text: "Вісник"
  url: /journal/
  landing: true
  layout: journal

- text: "Навколо"
  url: /calendar/
  landing: true

- text: "Друзі"
  url: /friends/
  landing: true

- text: "Про&nbsp;нас"
  url: /about/
  landing: true

- text: "+&nbsp;Написати"
  url: /write/
  landing: false

# Blog
featured_count: 1

# Build settings

markdown: kramdown
paginate: 10
paginate_path: /journal/:num
permalink: /journal/:categories/:year/:month/:day/:title/
sass:
    style: :compressed

gems:
  - jekyll-sitemap
