# Site settings

title: YOV
email: boretskyi@yov.com.ua
description: Могилянська колективна платформа
keywords: yov, могилянка, наукма, кма, брюховецький, квіт, мелешевич, студенти, спудеї, йов, іов, борецький, naukma, kma, академія, могилянська, могилянський, вісник, бонет, плацераці
baseurl: ""
url: "http://yov.com.ua"
twitter_username: yov_boretskiy
facebook_username: yovkma
email: boretskyi@yov.com.ua
facebook_app_id: 633629610107763

collections:
- events

# Navigation

navigation:
- text: "Вісник"
  url: /journal/
  landing: true
  layout: journal

- text: "Навколо"
  url: /calendar/
  landing: true

- text: "Друзі"
  url: /friends/
  landing: true

- text: "Про&nbsp;нас"
  url: /about/
  landing: true

- text: "+&nbsp;Написати"
  url: /write/
  landing: false

# Blog
featured_count: 1

# Build settings
markdown: kramdown
paginate: 5
paginate_path: /journal/:num
permalink: /journal/:categories/:year/:month/:day/:title/
sass:
    style: :compressed

gems:
  - jekyll-sitemap


# Prose.io
prose:
  rooturl: '_posts'
  media: 'media'
  ignore:
    - /journal
    - /_layouts
    - /_includes
  metadata:
    _posts:

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "featured"
        field:
          element: "checkbox"
          label: "Вибір редакції"
          value: false

      - name: "subtitle"
        field:
          element: "text"
          label: "Підзаголовок"

      - name: "author"
        field:
          element: "text"
          placeholder: "Йов Борецький"
          label: "Автор"

      - name: "author_link"
        field:
          element: "text"
          label: "Посилання на автора"
          placeholder: "http://facebook.com/username"

      - name: "image"
        field:
          element: "text"
          label: "Зображення на фон"
          placeholder: "/media/image.jpg"

      - name: "image_credit"
        field:
          element: "text"
          placeholder: "Reuters"
          label: "Автор зображення"
          value: null

      - name: "image_credit_link"
        field:
          element: "text"
          placeholder: "http://reuters.com"
          label: "Посилання на автора зображення"
          value: null

      - name: "tags"
        field:
          element: "multiselect"
          label: "Категорії"
          placeholder: "Choose Tags"
          options:
            - name: "Культура"
              value: "culture"
            - name: "Суспільство"
              value: "community"
            - name: "Наукма"
              value: "science"

-